name: 🍏 iOS Builds
on:
  workflow_call:
    inputs:
      build_profile:
        required: true
        default: 'build.gdbuild'
        type: string
  workflow_dispatch:
    inputs:
      build_profile:
        description: 'Path to custom build profile (e.g. build.gdbuild)'
        required: true
        default: 'build.gdbuild'
        type: string

# Global Settings
env:
  SCONS_FLAGS: >-
    production=yes
    dev_mode=yes
    tests=no
    debug_symbols=no

jobs:
  ios-template:
    # From https://docs.github.com/en/actions/how-tos/write-workflows/choose-where-workflows-run/choose-the-runner-for-a-job#choosing-github-hosted-runners
    runs-on: macos-latest
    name: ${{ matrix.name }}
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Template Release (target=template_release)
            target: template_release
          - name: Template Debug (target=template_debug)
            target: template_debug

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      # From https://github.com/actions/runner-images/blob/main/images/macos
      - name: Select Xcode 26
        run: sudo xcode-select -s /Applications/Xcode_26.0.1.app

      - name: Restore Godot build cache
        uses: ./.github/actions/godot-cache-restore
        with:
          cache-name: ios-${{ matrix.target }}
        continue-on-error: true

      - name: Setup Python and SCons
        uses: ./.github/actions/godot-deps

      - name: Compilation (arm64)
        uses: ./.github/actions/godot-build
        with:
          scons-flags: ${{ env.SCONS_FLAGS }} build_profile=${{ inputs.build_profile }}
          platform: ios
          target: ${{ matrix.target }}

      - name: Save Godot build cache
        uses: ./.github/actions/godot-cache-save
        with:
          cache-name: ios-${{ matrix.target }}
        continue-on-error: true

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: ios-${{ matrix.target }}
