name: 🐧 Linux Builds
on:
  workflow_call:
    inputs:
      build_profile:
        required: true
        default: 'build.gdbuild'
        type: string
  workflow_dispatch:
    inputs:
      build_profile:
        description: 'Path to custom build profile (e.g. build.gdbuild)'
        required: true
        default: 'build.gdbuild'
        type: string

# Global Settings
env:
  SCONS_FLAGS: >-
    dev_mode=yes
    "accesskit_sdk_path=${{ github.workspace }}/accesskit-c-0.18.0/"
  GODOT_CPP_BRANCH: 4.5
  DOTNET_NOLOGO: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  ASAN_OPTIONS: color=always:print_suppressions=1:suppressions=${{ github.workspace }}/misc/error_suppressions/asan.txt
  LSAN_OPTIONS: color=always:print_suppressions=1:suppressions=${{ github.workspace }}/misc/error_suppressions/lsan.txt
  TSAN_OPTIONS: color=always:print_suppressions=1:suppressions=${{ github.workspace }}/misc/error_suppressions/tsan.txt
  UBSAN_OPTIONS: color=always:print_suppressions=1:suppressions=${{ github.workspace }}/misc/error_suppressions/ubsan.txt

jobs:
  build-linux:
    # Stay one LTS before latest to increase portability of Linux artifacts.
    runs-on: ubuntu-22.04
    name: ${{ matrix.name }}
    timeout-minutes: 120
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Template Release (target=template_release)
            cache-name: linux-template-release
            target: template_release
            bin: ./bin/godot.linuxbsd.template_release.x86_64
            artifact: true

          - name: Template Debug (target=template_debug)
            cache-name: linux-template-debug
            target: template_debug
            bin: ./bin/godot.linuxbsd.template_debug.x86_64
            artifact: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup dependencies
        run: |
          sudo apt-get update
          sudo apt-get install libwayland-bin  # TODO: Figure out somehow how to embed this one.
          if [ "${{ matrix.proj-test }}" == "true" ]; then
            sudo apt-get install mesa-vulkan-drivers
          fi

      - name: Free disk space on runner
        run: |
          echo "Disk usage before:" && df -h
          sudo rm -rf /usr/local/lib/android
          echo "Disk usage after:" && df -h

      - name: Restore Godot build cache
        uses: ./.github/actions/godot-cache-restore
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Setup Python and SCons
        uses: ./.github/actions/godot-deps

      - name: Download pre-built AccessKit
        uses: dsaltares/fetch-gh-release-asset@1.1.2
        with:
          repo: AccessKit/accesskit-c
          version: tags/0.18.0
          file: accesskit-c-0.18.0.zip
          target: accesskit-c-0.18.0/accesskit_c.zip

      - name: Extract pre-built AccessKit
        run: unzip -o accesskit-c-0.18.0/accesskit_c.zip

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          scons-flags: ${{ env.SCONS_FLAGS }} ${{ matrix.scons-flags }} build_profile=${{ inputs.build_profile }}
          platform: linuxbsd
          target: ${{ matrix.target }}

      - name: Save Godot build cache
        uses: ./.github/actions/godot-cache-save
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Prepare artifact
        if: matrix.artifact
        run: |
          strip bin/godot.*
          chmod +x bin/godot.*

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        if: matrix.artifact
        with:
          name: ${{ matrix.cache-name }}
